spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  flyway:
    locations: classpath:/db/migration
    enabled: true
  batch:
    job:
      enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom:
  meilisearch:
    url: ${MEILISEARCH_URL}
    api-key: ${MEILISEARCH_API_KEY}
    index:
      memos:
        name: ${MEILISEARCH_INDEX_MEMOS_NAME}
        version: ${MEILISEARCH_INDEX_MEMOS_VERSION}
      questions:
        name: ${MEILISEARCH_INDEX_QUESTIONS_NAME}
        version: ${MEILISEARCH_INDEX_QUESTIONS_VERSION}


