spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:memocode;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.transaction.interceptor: TRACE