---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
http.host: 127.0.0.1

node.name: logstash

queue.type: persisted
queue.page_capacity: 64mb
queue.max_bytes: 1gb

pipeline.batch.size: 20
#pipeline.batch.delay: 1000
pipeline.workers: 1
